services:
  - type: web
    name: dash-analytics-app
    runtime: docker
    region: oregon  # Choose a region
    plan: free
    envVars:
      - key: DATABASE_CONNECTION_STRING
        sync: true
    buildCommand: docker build -t dash-app .
    startCommand: docker run -p 8050:8050 dash-app
